name: CI

on:
  push:
    branches: -main
  pull_request:
    branches: -main 

jobs:
  check-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v4

    - name: Setup Nodes.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        npm install
    - name: Check project
      run: echo "Project dependencies installed successfully"